import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
	docs: [
		"intro",
		"install",
		{
			type: "category",
			label: "Stories",
			collapsed: false,
			link: {
				type: "generated-index",
			},
			items: ["usage/writing-stories", "usage/controls", "usage/typechecking"],
		},
		{
			type: "category",
			label: "Frameworks",
			collapsed: false,
			link: {
				type: "generated-index",
			},
			items: [
				{
					type: "autogenerated",
					dirName: "usage/frameworks",
				},
			],
		},
		{
			type: "category",
			label: "Contributing",
			link: {
				type: "generated-index",
			},
			items: [
				{
					type: "autogenerated",
					dirName: "contributing",
				},
			],
		},
	],
};

export default sidebars;
