import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// The docs content is generated from the Obsidian vault (see
// scripts/build-docs.mjs), so the sidebar is autogenerated from the resulting
// directory tree rather than hand-maintained. Use _category_.json files or
// frontmatter sidebar_position in the vault to control ordering and labels.
const sidebars: SidebarsConfig = {
	docs: [
		{
			type: "autogenerated",
			dirName: ".",
		},
	],
};

export default sidebars;
