import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// The docs are read straight from the Obsidian vault (docs.path =
// '../obsidian-vault'), so the sidebar is autogenerated from the vault's
// directory tree. docs.sidebarItemsGenerator (see src/sidebar/obsidian.mjs)
// then post-processes that tree to relabel items from each note's Obsidian
// alias, keeping the vault free of Docusaurus-specific metadata.
const sidebars: SidebarsConfig = {
	docs: [
		{
			type: "autogenerated",
			dirName: ".",
		},
	],
};

export default sidebars;
