return {
  version = 1,
  package = {
    {
      name = "lute",
      rev = "0.1.0-nightly.20260408",
      source = "https://github.com/luau-lang/lute/archive/0.1.0-nightly.20260408.zip",
      sourceKind = "github",
    },
    {
      name = "flipbook-batteries",
      rev = "bump-lute-and-fix-api-usage",
      source = "https://github.com/flipbook-labs/flipbook-batteries/archive/bump-lute-and-fix-api-usage.zip",
      sourceKind = "github",
    },
  },
}