return {
  version = 1,
  package = {
    {
      name = "rbxasset",
      rev = "MUS-2390-rewrite-with-lute",
      source = "https://github.com/Roblox/rbxasset/archive/MUS-2390-rewrite-with-lute.zip",
      sourceKind = "github",
    },
    {
      name = "flipbook-batteries",
      rev = "v0.5.0",
      source = "https://github.com/flipbook-labs/flipbook-batteries/archive/v0.5.0.zip",
      sourceKind = "github",
    },
  },
}