[docusaurus]
tagline = "A storybook plugin for Roblox"

[home]
enabled = true

[[home.features]]
title = "Isolate your UI"
description = "With flipbook you can isolate distinct parts of your game's UI to hammer out edge cases and complex states without having to run through the whole UI"
# image=""

[[home.features]]
title = "Controls"
description = "Set custom controls that your stories can respond to while iterating to quickly toggle states and provide custom input without changing the story"
# image=""

[[home.features]]
title ="Support for Hoarcekat"
description = "Bring your existing stories from Hoarcekat over to flipbook by adding a Storybook to set them up."
# image=""
