[docusaurus]
tagline = "Storybook plugin for Roact development"

[home]
enabled = true

[[home.features]]
title = "Build UI faster"
description = "With flipbook you can quickly iterate on Roact components in an isolated, sandboxed environment to streamline the process of creating reusable UI components."
# image=""

[[home.features]]
title = "Controls"
description = "Set custom controls that your stories can respond to while iterating to quickly toggle states and provide custom input without changing the story"
# image=""

[[home.features]]
title ="Support for Hoarcekat"
description = "Bring your existing stories from Hoarcekat over to flipbook by adding a Storybook to set them up."
# image=""