name = "flipbook_labs/flipbook_workspace"
version = "2.0.0"
description = "Storybook plugin for Roblox UI"
authors = ["Marin Minnerly", "pasheley"]
repository = "https://github.com/flipbook-labs/flipbook"
license = "MIT"
private = true
workspace_members = ["packages/*"]

[target]
environment = "luau"

[indices]
default = "https://github.com/daimond113/pesde-index"
