name = "flipbook_labs/flipbook"
version = "2.0.0"
description = "Storybook plugin for Roblox UI"
authors = ["Marin Minnerly", "pasheley"]
repository = "https://github.com/flipbook-labs/flipbook"
license = "MIT"
pesde_version = "0.5.0-rc.16"

[target]
environment = "roblox"
lib = "build/init.server.luau"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
ModuleLoader = { wally = "wally#flipbook-labs/module-loader", version = "^0.6.2" }
React = { wally = "wally#jsdotlua/react", version = "^17.2.0" }
ReactRoblox = { wally = "wally#jsdotlua/react-roblox", version = "^17.2.0" }
ReactSpring = { wally = "wally#chriscerie/react-spring", version = "^2.0.0" }
Sift = { wally = "wally#csqrl/sift", version = "^0.0.9" }
Storyteller = { wally = "wally#flipbook-labs/storyteller", version = "^0.5.0" }
t = { wally = "wally#osyrisrblx/t", version = "^3.1.1" }

[dev_dependencies]
Fusion = { wally = "wally#elttob/fusion", version = "^0.2.0" }
Jest = { wally = "wally#jsdotlua/jest", version = "^3.6.1-rc.2" }
JestGlobals = { wally = "wally#jsdotlua/jest-globals", version = "^3.6.1-rc.2" }
Roact = { wally = "wally#roblox/roact", version = "^1.4.4" }
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
