[package]
name = "FlipbookCore"
content_root = "build"
version = "2.2.5"
files = ["*"]
publish = true

authors = ["Marin Minnerly <dminnerly@roblox.com>"]
documentation = "https://flipbook-labs.github.io/flipbook"
homepage = "https://flipbook-labs.github.io/flipbook"
readme = "README.md"
repository = "https://github.com/Roblox/flipbook"

[config]
registry_index = true

[dependencies]
# Foundation = "*"
# React = "17.0.6"
# ReactOtter = "1.3.3"
# ReactRoblox = "17.0.6"
# ReactUtils = "1.9.0"
# Signals = "0.5.0"
# SignalsReact = "0.5.0"
