name = "flipbook"

[[inputs]]
glob = "img/Core/**/*.png"
codegen = true
codegen-path = "src/assets.luau"
codegen-base-path = "img/Core"
packable = true

[[inputs]]
glob = "img/DeviceEmulator/**/*.png"
codegen = true
codegen-path = "src/assets.luau"
codegen-base-path = "img"
packable = true
