name = "flipbook_labs/flipbook_code_samples"
version = "2.0.0"
private = true

[target]
environment = "roblox"

[scripts]
roblox_sync_config_generator = ".pesde/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/sourcemap_generator.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
React = { wally = "wally#jsdotlua/react", version = "^17.2.0" }
Reactroblox = { wally = "wally#jsdotlua/react-roblox", version = "^17.2.0" }
Fusion = { wally = "wally#elttob/fusion", version = "^0.2.0" }
Roact = { wally = "wally#roblox/roact", version = "^1.4.4" }
Storyteller = { wally = "wally#flipbook-labs/storyteller", version = "^0.5.0" }
