[package]
name = "flipbook-labs/flipbook-example"
version = "0.1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["*"]

[dependencies]
React = "jsdotlua/react@17.0.2"
ReactRoblox = "jsdotlua/react-roblox@17.0.2"
Roact = "roblox/roact@1.4.4"
Sift = "csqrl/sift@0.0.8"
