return {
	embedFlipbook = require("@root/actions/embedFlipbook"),
	getControls = require("@root/actions/getControls"),
	getCurrentStory = require("@root/actions/getCurrentStory"),
	listStories = require("@root/actions/listStories"),
	listStorybooks = require("@root/actions/listStorybooks"),
	openStory = require("@root/actions/openStory"),
	openViewport = require("@root/actions/openViewport"),
	openWidget = require("@root/actions/openWidget"),
	setControls = require("@root/actions/setControls"),
}
