[package]
name = "flipbook-labs/flipbook"
version = "2.4.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["*"]

[dependencies]
Storyteller = "flipbook-labs/storyteller@1.10.1"

# dev dependencies
Jest = "jsdotlua/jest@3.10.0"
JestGlobals = "jsdotlua/jest-globals@3.10.0"
