[package]
name = "FlipbookCore"
content_root = "build"
version = "2.2.0"
files = ["*"]
publish = true

authors = ["Marin Minnerly <me@vocksel.com>"]
documentation = "https://flipbook-labs.github.io/flipbook"
homepage = "https://flipbook-labs.github.io/flipbook"
readme = "README.md"
repository = "https://github.com/flipbook-labs/flipbook"

[config]
registry_index = true

[dependencies]
