[package]
name = "flipbook-labs/flipbook-core"
version = "2.2.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["*"]

[dependencies]
Highlighter = "boatbomber/highlighter@0.9.0"
ModuleLoader = "flipbook-labs/module-loader@0.7.0"
React = "jsdotlua/react@17.0.2"
ReactRoblox = "jsdotlua/react-roblox@17.0.2"
ReactSpring = "chriscerie/react-spring@2.0.0"
RoactCompat = "jsdotlua/react-roblox@17.0.2"
Sift = "csqrl/sift@0.0.8"
Storyteller = "flipbook-labs/storyteller@1.1.1"
t = "osyrisrblx/t@3.0.0"
Markdown = "aloroid/markdown@0.1.2"

# dev dependencies
Roact = "roblox/roact@1.4.4"
Jest = "jsdotlua/jest@3.10.0"
JestGlobals = "jsdotlua/jest-globals@3.10.0"
