-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	checkmark = "rbxassetid://8484527786",
	["chevron-right"] = "rbxassetid://8472731876",
	["double-arrow"] = "rbxassetid://8492343246",
	folder = "rbxassetid://8472668100",
	story = "rbxassetid://8481250291",
	storybook = "rbxassetid://8472668370",
}