-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	ChevronRight = {
		Image = "rbxassetid://10175334645",
		ImageRectOffset = Vector2.new(65, 49),
		ImageRectSize = Vector2.new(32, 32),
	},
	Component = {
		Image = "rbxassetid://10175334645",
		ImageRectOffset = Vector2.new(0, 114),
		ImageRectSize = Vector2.new(32, 32),
	},
	Folder = {
		Image = "rbxassetid://10175334645",
		ImageRectOffset = Vector2.new(157, 0),
		ImageRectSize = Vector2.new(32, 32),
	},
	IconLight = {
		Image = "rbxassetid://10175334645",
		ImageRectOffset = Vector2.new(114, 0),
		ImageRectSize = Vector2.new(42, 42),
	},
	Magnify = {
		Image = "rbxassetid://10175334645",
		ImageRectOffset = Vector2.new(65, 0),
		ImageRectSize = Vector2.new(48, 48),
	},
	Minify = {
		Image = "rbxassetid://10175334645",
		ImageRectOffset = Vector2.new(0, 65),
		ImageRectSize = Vector2.new(48, 48),
	},
	Search = {
		Image = "rbxassetid://10175334645",
		ImageRectOffset = Vector2.new(114, 43),
		ImageRectSize = Vector2.new(32, 32),
	},
	Storybook = {
		Image = "rbxassetid://10175334645",
		ImageRectOffset = Vector2.new(65, 82),
		ImageRectSize = Vector2.new(32, 32),
	},
	flipbook = {
		Image = "rbxassetid://10175334645",
		ImageRectOffset = Vector2.new(0, 0),
		ImageRectSize = Vector2.new(64, 64),
	},
}
