name: Docs

on:
  pull_request:
  push:
    branches:
      - main

env:
  REPO_URL: github.com/vocksel/flipbook

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v2.5.1

      - name: Install Moonwave
        run: npm install -g moonwave

      - name: Extract
        run: moonwave-extractor extract src

      - name: Build
        run: moonwave build

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Use GITHUB_TOKEN to allow pushing
        run: git remote set-url origin https://github-actions[bot]:${{ env.GITHUB_TOKEN }}@${{ env.REPO_URL }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        run: moonwave build --publish
