name: Docs

on:
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: Roblox/setup-foreman@v3
        with:
          allow-external-github-orgs: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm ci
        working-directory: docs

      - name: Build
        run: npm run build
        working-directory: docs

      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build

  deploy-docs:
    needs: build-docs
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
