name: Feedback

on:
  repository_dispatch:
    types: [post_feedback]
  pull_request:

jobs:
  post-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Post feedback
        run: |
          gh issue create \
            --title "$TITLE" \
            --body "$BODY" \
            --label "feedback"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: ${{ github.event.client_payload.title || 'Title' }}
          BODY: |
            > ${{ github.event.client_payload.body }}

            Build info:

            - Version: ${{ github.event.client_payload.buildVersion }}
            - Channel: ${{ github.event.client_payload.buildChannel }}
            - Hash: ${{ github.event.client_payload.buildHash }}

            <sub>Posted on behalf of Roblox user ${{ github.event.client_payload.userId }}</sub>
