name: Release

on:
  pull_request:
  release:
    types: [published]
  push:
    branches:
      - main

jobs:
  build-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v6
        with:
          fetchViaCommits: true
          configurationJson: |
            {
                "categories": [
                  {
                    "title": "## 🚀 Features",
                    "labels": ["feature"]
                  },
                  {
                    "title": "## 🐛 Fixes",
                    "labels": ["fix"]
                  },
                  {
                    "key": "tests",
                    "title": "## 🧪 Tests",
                    "labels": ["test"]
                  },
                  {
                    "title": "## 🧪 Tests and some 🪄 Magic",
                    "labels": ["test", "magic"],
                    "exclude_labels": ["no-magic"],
                    "exhaustive": true,
                    "exhaustive_rules": "false",
                    "empty_content": "- no matching PRs",
                    "rules": [
                      {
                        "pattern": "open",
                        "on_property": "status",
                        "flags": "gu"
                      }
                    ]
                  }
                ],
                "ignore_labels": [
                  "ignore"
                ],
                "sort": {
                  "order": "ASC",
                  "on_property": "mergedAt"
                },
                "template": "#{{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
                "pr_template": "- #{{TITLE}}\n   - PR: ##{{NUMBER}}",
                "empty_template": "- no changes",
                "label_extractor": [
                  {
                    "pattern": "(.) (.+)",
                    "target": "$1",
                    "flags": "gu"
                  },
                  {
                    "pattern": "\\[Issue\\]",
                    "on_property": "title",
                    "method": "match"
                  }
                ],
                "duplicate_filter": {
                  "pattern": "\\[ABC-....\\]",
                  "on_property": "title",
                  "method": "match"
                },
                "reference": {
                  "pattern": ".*\\ \\#(.).*",
                  "on_property": "body",
                  "method": "replace",
                  "target": "$1"
                },
                "transformers": [
                  {
                    "pattern": "[\\-\\*] (\\[(...|TEST|CI|SKIP)\\])( )?(.+?)\n(.+?[\\-\\*] )(.+)",
                    "target": "- $4\n  - $6"
                  }
                ],
                "trim_values": false,
                "max_tags_to_fetch": 200,
                "max_pull_requests": 200,
                "max_back_track_time_days": 365,
                "exclude_merge_branches": [
                  "Owner/qa"
                ],
                "tag_resolver": {
                  "method": "semver",
                  "filter": {
                    "pattern": "api-(.+)",
                    "flags": "gu"
                  }
                },
                "base_branches": [
                  "dev"
                ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Output changelog to job summary
        run: echo "${{ steps.github_release.outputs.changelog }}" >> $GITHUB_STEP_SUMMARY

  publish-github-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ github.event.release }}
    steps:
      - uses: actions/checkout@v4

      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          version: v1.2.0

      - name: Get model file name
        run: |
          name=$(jq -r .name default.project.json)
          echo "MODEL_FILE=$name.rbxm" >> $GITHUB_ENV

      - name: Install dependencies
        run: lute scripts/install.luau

      - name: Create .env
        run: cp .env.template .env

      - name: Build
        run: lute scripts/build.luau --channel prod --output ${{ env.MODEL_FILE }}

      - uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.MODEL_FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-plugin:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency: production
    environment:
      name: roblox-creator-store
      url: https://create.roblox.com/store/asset/8517129161
    env:
      LOG_LEVEL: debug
    if: github.event.release
    steps:
      - uses: actions/checkout@v4

      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          version: v1.1.1

      - name: Install dependencies
        run: lute scripts/install.luau

      - name: Create .env
        run: cp .env.template .env

      - name: Publish release to Creator Store
        run: lune run publish-plugin --channel prod --apiKey ${{ secrets.ROBLOX_API_KEY }}

  publish-nightly-plugin:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency: nightly
    environment:
      name: roblox-creator-store-dev
      url: https://create.roblox.com/store/asset/88523969718241
    env:
      LOG_LEVEL: debug
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          version: v1.2.0

      - name: Install dependencies
        run: lute scripts/install.luau

      - name: Create .env
        run: cp .env.template .env

      - name: Publish nightly build to Creator Store
        run: lune run publish-plugin --channel dev --apiKey ${{ secrets.ROBLOX_API_KEY }}

  publish-smoketest-plugin:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency: ${{ github.ref }}
    environment:
      name: roblox-creator-store-smoketest
    env:
      LOG_LEVEL: debug
    steps:
      - uses: actions/checkout@v4

      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          version: v1.1.1

      - name: Install dependencies
        run: lute scripts/install.luau

      - name: Create .env
        run: cp .env.template .env

      - name: Publish release to Creator Store
        run: lune run publish-plugin --smoketest --channel prod --apiKey ${{ secrets.ROBLOX_API_KEY }}
