name: Release

on:
  pull_request:
  release:
    types: [published]
  push:
    branches:
      - main

jobs:
  build-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Prepare changelog config
        run: |
          jq -n \
            --rawfile template .github/changelog_template.md \
            --slurpfile config .github/release-changelog-config.json \
            '$config[0] + {template: $template}' \
            > .github/release-config-with-template.json

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v6
        with:
          fetchViaCommits: true
          configuration: .github/release-config-with-template.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo changelog
        run: echo "${{ steps.github_release.outputs.changelog }}"

      - name: Output changelog to job summary
        run: echo "${{ steps.github_release.outputs.changelog }}" >> $GITHUB_STEP_SUMMARY

  publish-github-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ github.event.release }}
    steps:
      - uses: actions/checkout@v4

      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          version: v1.2.0

      - name: Get model file name
        run: |
          name=$(jq -r .name default.project.json)
          echo "MODEL_FILE=$name.rbxm" >> $GITHUB_ENV

      - name: Install dependencies
        run: lute run install

      - name: Create .env
        run: cp .env.template .env

      - name: Build
        run: lute run build --channel prod --output ${{ env.MODEL_FILE }}

      - uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.MODEL_FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-plugin:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency: production
    environment:
      name: roblox-creator-store
      url: https://create.roblox.com/store/asset/8517129161
    env:
      LOG_LEVEL: debug
    if: github.event.release
    steps:
      - uses: actions/checkout@v4

      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          version: v1.1.1

      - name: Install dependencies
        run: lute run install

      - name: Create .env
        run: cp .env.template .env

      - name: Publish release to Creator Store
        run: lune run publish-plugin --channel prod --apiKey ${{ secrets.ROBLOX_API_KEY }}

  publish-nightly-plugin:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency: nightly
    environment:
      name: roblox-creator-store-dev
      url: https://create.roblox.com/store/asset/88523969718241
    env:
      LOG_LEVEL: debug
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          version: v1.2.0

      - name: Install dependencies
        run: lute run install

      - name: Create .env
        run: cp .env.template .env

      - name: Publish nightly build to Creator Store
        run: lune run publish-plugin --channel dev --apiKey ${{ secrets.ROBLOX_API_KEY }}

  publish-smoketest-plugin:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency: ${{ github.ref }}
    environment:
      name: roblox-creator-store-smoketest
    env:
      LOG_LEVEL: debug
    steps:
      - uses: actions/checkout@v4

      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          version: v1.1.1

      - name: Install dependencies
        run: lute run install

      - name: Create .env
        run: cp .env.template .env

      - name: Publish release to Creator Store
        run: lune run publish-plugin --smoketest --channel prod --apiKey ${{ secrets.ROBLOX_API_KEY }}
