name: Deploy Storybook Experience

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.event.action != 'closed'
    concurrency:
      group: storybook-pr-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v6

      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          version: v1.2.0

      - name: Install dependencies
        run: lute run install

      - name: Create .env
        run: cp .env.template .env

      - name: Deploy storybook place
        env:
          ROBLOX_API_KEY: ${{ secrets.ROBLOX_API_KEY }}
        run: lute run deploy-storybook
