name: Sync

on:
  workflow_dispatch:
  schedule:
    # Scheduled to run everyday at 8am UTC.
    - cron: "0 8 * * *"
  pull_request:

jobs:
  sync-upstream-changes:
    runs-on: [self-hosted, generic-linux]
    container: docker.artifactory.rbx.com/rbx-lua-build-tools:v1.0.1
    permissions:
      contents: write
    timeout-minutes: 5
    steps:
      - uses: Roblox-ActionsCache/tibdex-github-app-token@v1.4.0
        id: setup_token
        with:
          app_id: ${{ secrets.TOKENS_APP_LUA_ECOSYSTEM_DEPENDENCIES_ID }}
          private_key: ${{ secrets.TOKENS_APP_LUA_ECOSYSTEM_DEPENDENCIES_KEY }}
          repository: Roblox/rotriever-proxy-index

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/flipbook-labs/flipbook
          git remote -v

      - name: Sync `upstream` branch with upstream changes
        run: |
          git fetch upstream main
          git checkout -B upstream upstream/main
          git reset --hard upstream/main

      - name: Push changes to `upstream` branch
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
        run: git push origin upstream --force

  build:
    needs: [sync-upstream-changes]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      upstream-version: ${{ steps.export_upstream_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.ref || 'roblox' }}

      - uses: actions/checkout@v4
        with:
          ref: upstream
          path: upstream

      - uses: Roblox-ActionsCache/tibdex-github-app-token@v1.4.0
        id: setup_token
        with:
          app_id: ${{ secrets.TOKENS_APP_LUA_ECOSYSTEM_DEPENDENCIES_ID }}
          private_key: ${{ secrets.TOKENS_APP_LUA_ECOSYSTEM_DEPENDENCIES_KEY }}
          repository: Roblox/rotriever-proxy-index

      - uses: Roblox/setup-foreman@v3
        with:
          token: ${{ steps.setup_token.outputs.token }}
          allow-external-github-orgs: true

      - name: Export upstream version
        id: export_upstream_version
        run: |
          version=$(grep '^version = ' upstream/wally.toml | cut -d'"' -f2)
          echo $version
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Install dependencies
        working-directory: upstream
        run: lune run install

      - name: Build
        working-directory: upstream
        # The rbxm file isn't actually needed, we just pass the flag so the build
        # script doesn't try to build to the Roblox Studio plugins folder (which
        # doesn't exist in CI and causes an error)
        run: lune run build --channel prod --target rotriever --output Flipbook.rbxm

      - uses: actions/upload-artifact@v4
        with:
          name: flipbook-core-build
          path: upstream/workspace/flipbook-core/build

  create-pr:
    needs: [build]
    runs-on: [self-hosted, generic-linux]
    container: docker.artifactory.rbx.com/rbx-lua-build-tools:v1.0.1
    permissions:
      contents: write
      pull-requests: write
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.ref || 'roblox' }}

      - uses: Roblox-ActionsCache/tibdex-github-app-token@v1.4.0
        id: setup_token
        with:
          app_id: ${{ secrets.TOKENS_APP_LUA_ECOSYSTEM_DEPENDENCIES_ID }}
          private_key: ${{ secrets.TOKENS_APP_LUA_ECOSYSTEM_DEPENDENCIES_KEY }}
          repository: Roblox/rotriever-proxy-index

      - uses: Roblox/setup-foreman@v3
        with:
          token: ${{ steps.setup_token.outputs.token }}
          allow-external-github-orgs: true

      - uses: actions/download-artifact@v4
        with:
          name: flipbook-core-build
          path: build

      - name: Sync major and minor version with upstream
        run: lune run sync-version ${{ needs.build.outputs.upstream-version }}

      - name: Bump version in rotriever.toml
        run: lune run bump-version patch

      - name: Create pull request
        uses: roblox-actionscache/peter-evans-create-pull-request@v7.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: roblox
          add-paths: |
            build/
            rotriever.toml
          commit-message: "Sync upstream changes"
          branch: sync-upstream-changes
          title: "[AUTO-GENERATED] Sync with upstream Flipbook changes"
          body: |
            Updating the Roblox fork of Flipbook with the latest changes from the upstream repository.

            This pull request was generated by [this run](https://github.com/Roblox/lua-apps/actions/runs/${{ github.run_id }}).
          delete-branch: true
          reviewers: vocksel
